
export const assets = {

  home: {
    hero: {
      avatarSmile: require("@images/home/hero/gm-avatar.gif"),
      avatar: require("@images/home/hero/avatar.png"),
      quadrilateral: require("@images/home/hero/quadrilateral.webp"),
      triangle: require("@images/home/hero/triangle.webp"),
      twistedTorus: require("@images/home/hero/twisted-torus.webp"),
      zigZag: require("@images/home/hero/zig-zag.webp"),
      mobile: require("@images/home/hero/S21FE.png"),
      starbucks: require("@images/home/hero/Starbucks Coffee Cup.webp"),
      pokeball: require("@images/home/hero/pokeball.png"),
      dev: require("@images/home/hero/dev.png"),
      music: require("@images/home/hero/music.webp"),
      infinity: require("@images/home/hero/infinity.webp"),
    },
    letsConnect: {
      avatarBigSmile: require("@images/home/letsConnect/gm-avatar.png"),
      dribble: require("@images/home/letsConnect/dribble.webp"),
      github: require("@images/home/letsConnect/github.webp"),
      gmail: require("@images/home/letsConnect/gmail.webp"),
      instagram: require("@images/home/letsConnect/instagram.webp"),
      linkedin: require("@images/home/letsConnect/linkedin.webp"),
      x: require("@images/home/letsConnect/X.svg"),
    },
    myLatestProject: {
      figma: require("@images/home/myLatestProject/figma.webp"),
      rocket: require("@images/home/myLatestProject/rocket.webp"),
      suitcase: require("@images/home/myLatestProject/suitcase.webp"),
      projects: {
        portfolioWebsite: require("@images/home/myLatestProject/projects/portfolio-website.webp"),
      },
    },
    quote: {
      bulb: require("@images/home/quote/bulb.webp"),
      heart: require("@images/home/quote/heart.webp"),
      paintKit: require("@images/home/quote/paint-kit.webp"),
      teaCup: require("@images/home/quote/tea-cup.webp"),
    },
    technologyStack: {
      flutter: require("@images/home/technologyStack/Flutter.png"),
      figma: require("@images/home/technologyStack/figma.png"),
      git: require("@images/home/technologyStack/github.png"),
      firebase: require("@images/home/technologyStack/firebase.png"),
      androidstudio: require("@images/home/technologyStack/AndroidStudio.webp"),
      java: require("@images/home/technologyStack/java.png"),
      sql: require("@images/home/technologyStack/sql.png"),
      springboot: require("@images/home/technologyStack/SpringBoot.png"),
      expo: require("@images/home/technologyStack/expo.webp"),
      expressJs: require("@images/home/technologyStack/express-js.webp"),
      javascript: require("@images/home/technologyStack/javascript.webp"),
      laravel: require("@images/home/technologyStack/laravel.webp"),
      nextJs: require("@images/home/technologyStack/next-js.webp"),
      planetScale: require("@images/home/technologyStack/planet-scale.webp"),
      prisma: require("@images/home/technologyStack/prisma.webp"),
      reactJs: require("@images/home/technologyStack/react-js.webp"),
      reactNative: require("@images/home/technologyStack/react-native.webp"),
      tailwindCss: require("@images/home/technologyStack/tailwindcss.webp"),
      typescript: require("@images/home/technologyStack/typescript.webp"),
    },
  },
};
